pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                bat "copy C:\ProgramData\Jenkins\.jenkins\workspace\maven-project-pipeline\target\my-app-1.0-SNAPSHOT.jar C:\ProgramData\Jenkins\.jenkins\workspace\maven-project-pipeline\my-app-1.0-SNAPSHOT.jar"
            }
        }
    }
}
