pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat 'C:\\Program Files\\apache-maven-3.9.6\\bin\\mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                bat 'C:\\Program Files\\apache-maven-3.9.6\\bin\\mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                bat "copy target\\my-app-1.0-SNAPSHOT.jar ."
            }
        }
    }
}
